"""
Spherical varieties assembled orbit by orbit (PLAN.md S6d, docs/spherical.md).

T-fixed points of a spherical variety can lie in non-closed G-orbits (for
P^1 x P^1 > SL_2/T two of them lie in the open orbit), so the fixed-point
data is assembled orbit by orbit. A G-orbit O contains T-fixed points iff
its stabilizers contain a maximal torus; then, for a base point x with
stabilizer H > T,
    O^T = N_G(T).x = W/W_H,   W_H = N_H(T)/T,
    T_{w.x} X = w(Phi_G - Phi_H) + w(N_x),
where Phi_H are the roots of H and N_x is the normal space to O at x (a
W_H-invariant multiset of weights). So the whole of X^T is determined by
one base point per such orbit.

For a wonderful variety with spherical roots Sigma and S^p (the simple roots
of the parabolic P(X)), the orbit O_I (I c Sigma) fibres over G/P_I with
fibre the satellite L_I/H_{L,I}, where L_I is the Levi subgroup on
S^p + supp(I). The orbit has T-fixed points iff the satellite does, and
then (docs/spherical.md, section 3)
    Phi_H = (Phi^+ - Phi_{L_I}) + Phi_{H_{L,I}},
    N_x   = the W_{L_I}-averages of -gamma, gamma in Sigma - I,
the latter provided the reflections of W_{H_{L,I}} span the roots of L_I
(checked; otherwise the normal weights are not determined by this data).
All weights are in simple-root coordinates of G (the torus of G_ad).
"""

from dataclasses import dataclass
from fractions import Fraction
from itertools import combinations

from bbcells.algebra import IntPoly
from bbcells.core import FixedPointData
from bbcells.frontends.flag import word_label
from bbcells.linalg import null_space, rank as matrix_rank, solve
from bbcells.rootsystem import RootSystem

def _negate(v):
    return tuple(-c for c in v)


def root_subsystem(R, generators):
    """the root subsystem generated by the given roots (closure under their
    reflections), as a set of roots in simple-root coordinates; two long
    roots of G_2 generate the A_2 of all long roots
    >>> sorted(root_subsystem(RootSystem("G2"), [(0, 1), (3, 1)]))
    [(-3, -2), (-3, -1), (0, -1), (0, 1), (3, 1), (3, 2)]
    """
    def reflect(beta, gamma):
        c = R.coroot_pairing(beta, gamma)
        return tuple(g - c * b for g, b in zip(gamma, beta))

    roots = set()
    for g in generators:
        roots.add(tuple(g))
        roots.add(_negate(g))
    frontier = list(roots)
    while frontier:
        new = []
        for gamma in frontier:
            for beta in list(roots):
                image = reflect(beta, gamma)
                if image not in roots:
                    roots.add(image)
                    new.append(image)
        frontier = new
    return roots


def _all_roots(R):
    return set(R.positive_roots) | {_negate(b) for b in R.positive_roots}


def _reflection(R, beta, v):
    """s_beta(v) for a root beta and any vector v (simple-root coordinates)"""
    c = 2 * R.inner(beta, v) / R.inner(beta, beta)
    if c.denominator != 1:
        raise ValueError("s_%r does not preserve the lattice at %r" % (beta, v))
    return tuple(x - int(c) * b for x, b in zip(v, beta))


def homogeneous_fixed_points(cartan_type, generators=(), component_reflections=(),
                             unipotent_roots=(), normal=(), component_elements=()):
    """fixed points of T on an orbit G/H with T c H, and their tangent weights.

    H is described by its roots: the root subsystem generated by `generators`
    (the reductive part, Borel-de Siebenthal) and the W_H-orbits of
    `unipotent_roots`. W_H = N_H(T)/T is generated by the reflections of the
    subsystem, by `component_reflections` (roots whose reflections lie in
    N_H(T), e.g. Knop's <s_{a_1}>.SL(3) in G2) and by `component_elements`
    (Weyl group elements as words w = s_{i_1} ... s_{i_k}, 0-based, e.g. the
    swap of the two blocks of S(GL_2 x GL_2) in PGL_4). `normal` are the
    weights of the normal space of the orbit at eH. Returns {label: weights}
    over W/W_H, labelled by a minimal-length representative.
    >>> points = homogeneous_fixed_points("A1")                # SL_2/T
    >>> sorted(sorted(w) for w in points.values())
    [[(-1,), (1,)], [(-1,), (1,)]]
    >>> homogeneous_fixed_points("A2", unipotent_roots=[(1, 0), (0, 1), (1, 1)])["e"]  # G/B
    ((-1, -1), (-1, 0), (0, -1))
    >>> swap = (1, 0, 2, 1)                  # (13)(24) in S_4, normalizes A1 x A1
    >>> len(homogeneous_fixed_points("A3", [(1, 0, 0), (0, 0, 1)], component_elements=[swap]))
    3
    """
    R = RootSystem(cartan_type)
    roots = _all_roots(R)
    phi_sym = root_subsystem(R, generators)
    if not phi_sym <= roots:
        raise ValueError("the generators do not span a subsystem of roots")
    reflections = sorted(phi_sym) + [tuple(b) for b in component_reflections]
    if not all(b in roots for b in reflections):
        raise ValueError("component reflections must be in roots")
    words = [tuple(word) for word in component_elements]
    maps = ([lambda v, s=s: _reflection(R, s, v) for s in reflections] +
            [lambda v, word=word: R.apply_word(word, v) for word in words])
    for b in component_reflections:
        if {_reflection(R, tuple(b), g) for g in phi_sym} != phi_sym:
            raise ValueError("s_%r does not normalize the reductive part" % (tuple(b),))
    # Phi_H: the reductive part and the W_H-orbits of the unipotent roots
    phi_h, frontier = set(phi_sym), [tuple(b) for b in unipotent_roots]
    while frontier:
        beta = frontier.pop()
        if beta in phi_h:
            continue
        if beta not in roots:
            raise ValueError("%r is not a root" % (beta,))
        phi_h.add(beta)
        frontier.extend(f(beta) for f in maps)
    if {b for b in phi_h if _negate(b) in phi_h} != phi_sym:
        raise ValueError("the roots of H meet their negatives outside the reductive part: "
                         "H is not described by these generators")
    for a in phi_h:
        for b in phi_h:
            total = tuple(x + y for x, y in zip(a, b))
            if total in roots and total not in phi_h:
                raise ValueError("the roots of H are not closed: %r + %r" % (a, b))
    normal = [tuple(v) for v in normal]
    for f, name in zip(maps, reflections + words):
        if sorted(f(v) for v in normal) != sorted(normal):
            raise ValueError("the normal weights are not W_H-invariant (%r)" % (name,))
    complement = sorted(roots - phi_h)

    # the reflection part W_refl of W_H: by Dyer (Reflection subgroups of
    # Coxeter systems, 1990) each coset w W_refl has a unique element of
    # minimal length, the w with w(beta) > 0 for every positive root beta of
    # W_refl. The component elements normalize W_refl and glue its cosets.
    positive = set(R.positive_roots)
    phi_refl = root_subsystem(R, reflections)
    for word in words:
        if {R.apply_word(word, b) for b in phi_refl} != phi_refl:
            raise ValueError("%r does not normalize the reflection part of W_H" % (word,))
    positive_h = [b for b in phi_refl if b in positive]
    reps = coset_representatives(R, positive_h, words)
    points = {}
    for word, M in reps:
        points[word_label(word)] = (tuple(_apply(M, b) for b in complement) +
                                    tuple(_apply(M, v) for v in normal))
    return points


# Weyl group elements as integer matrices: the tuple of images of the simple
# roots (columns), acting on simple-root coordinates.

def _identity(r):
    return tuple(tuple(int(i == j) for i in range(r)) for j in range(r))


def _apply(M, v):
    return tuple(sum(c * col[k] for c, col in zip(v, M)) for k in range(len(M)))


def _left(R, i, M):
    """s_i o M"""
    return tuple(R.reflect(i, col) for col in M)


_COROOTS = {}


def _coroot_row(R, beta):
    """(<beta^vee, alpha_j>)_j, cached"""
    key = (R.name, beta)
    if key not in _COROOTS:
        _COROOTS[key] = tuple(R.coroot_pairing(beta, _unit_vector(j, R.rank))
                              for j in range(R.rank))
    return _COROOTS[key]


def _right_reflection(R, M, beta):
    """M o s_beta"""
    image = _apply(M, beta)
    row = _coroot_row(R, beta)
    return tuple(tuple(c - p * b for c, b in zip(col, image)) if p else col
                 for p, col in zip(row, M))


def _unit_vector(j, r):
    return tuple(int(k == j) for k in range(r))


def _is_negative(v):
    return all(c <= 0 for c in v)


_TABLES = {}


def _root_table(R):
    """sorted roots, their index, the simple reflections as permutations of
    the root indices, and the set of indices of positive roots (cached)"""
    if R.name not in _TABLES:
        roots = sorted(set(R.positive_roots) | {tuple(-c for c in b) for b in R.positive_roots})
        index = {b: i for i, b in enumerate(roots)}
        simple = [tuple(index[R.reflect(i, b)] for b in roots) for i in range(R.rank)]
        positive = frozenset(index[b] for b in R.positive_roots)
        _TABLES[R.name] = (roots, index, simple, positive)
    return _TABLES[R.name]


def coset_representatives(R, positive_h, component_words=(), limit=2000000):
    """[(reduced word, matrix)] of the minimal-length representatives of W/W_H,
    W_H generated by the reflections in the root subsystem with positive roots
    `positive_h` and by the elements `component_words` (which must normalize
    it). Never enumerates W: for a reflection subgroup W' and w minimal in
    w W', s_i w is minimal in its coset unless w^{-1}(alpha_i) is a positive
    root of W', in which case s_i w W' = w W' (Deodhar's lemma, which holds for
    reflection subgroups by Dyer's criterion); so a search by length over
    inverse permutations finds every representative with a reduced word.
    For A_2 and W_H = <s_1>: three cosets, the fixed points of SL_3/P_2 =
    Gr(2, 3); for W_H = 1 all of W:
    >>> R = RootSystem("A2")
    >>> [word for word, _ in coset_representatives(R, [(1, 0)])]
    [(), (1,), (0, 1)]
    >>> len(coset_representatives(R, []))
    6
    """
    roots, index, simple, positive = _root_table(R)
    n = len(roots)
    in_h = frozenset(index[b] for b in positive_h)
    simple_index = [index[_unit_vector(i, R.rank)] for i in range(R.rank)]
    identity = tuple(range(n))
    words = {identity: ()}                        # w^{-1} (as a permutation) -> word of w
    level = [identity]
    while level:
        new = []
        for v in level:
            for i in range(R.rank):
                image = v[simple_index[i]]        # w^{-1}(alpha_i)
                if image not in positive or image in in_h:
                    continue                      # shorter, or the same coset
                u = tuple(v[k] for k in simple[i])        # (s_i w)^{-1} = w^{-1} s_i
                if u not in words:
                    words[u] = (i,) + words[v]
                    new.append(u)
                    if len(words) > limit:
                        raise ValueError("more than %d cosets" % limit)
        level = new

    def forward(v):                               # w from w^{-1}
        w = [0] * n
        for k, image in enumerate(v):
            w[image] = k
        return tuple(w)

    reps = {forward(v): word for v, word in words.items()}
    if component_words:
        reflection = {b: tuple(index[_reflection(R, b, c)] for c in roots) for b in positive_h}
        glue = []
        for word in component_words:
            C = identity
            for i in reversed(word):
                C = tuple(simple[i][k] for k in C)            # s_i o C
            glue.append(C)
        h_indices = [index[b] for b in positive_h]

        def reduce(u):                            # the minimal representative of u W_refl
            while True:
                bad = next((b for b, k in zip(positive_h, h_indices) if u[k] not in positive),
                           None)
                if bad is None:
                    return u
                u = tuple(u[k] for k in reflection[bad])       # u o s_beta

        chosen, done = [], set()
        for w in sorted(reps, key=lambda w: (len(reps[w]), reps[w])):
            if w in done:
                continue
            orbit, stack = {w}, [w]
            while stack:
                U = stack.pop()
                for C in glue:
                    V = reduce(tuple(U[k] for k in C))         # U o C
                    if V not in orbit:
                        orbit.add(V)
                        stack.append(V)
            done |= orbit
            chosen.append(w)
    else:
        chosen = list(reps)
    result = []
    for w in chosen:
        word = reps[w]
        M = tuple(roots[w[k]] for k in simple_index)          # images of the simple roots
        result.append((word, M))
    result.sort(key=lambda item: (len(item[0]), item[0]))
    return result


def reduce_modulo(R, positive_h, word):
    """a reduced word of the minimal representative of w W_refl (w given by a
    word), W_refl the reflection subgroup with positive roots positive_h. In
    A_2 modulo <s_1>: s_1 -> e, s_2 s_1 -> s_2, w_0 = s_1 s_2 s_1 -> s_1 s_2:
    >>> R = RootSystem("A2")
    >>> [reduce_modulo(R, [(1, 0)], word) for word in [(0,), (1, 0), (0, 1, 0)]]
    [(), (1,), (0, 1)]
    """
    M = _identity(R.rank)
    for i in reversed(word):
        M = _left(R, i, M)
    while True:
        bad = next((b for b in positive_h if _is_negative(_apply(M, b))), None)
        if bad is None:
            return _word_of(R, M)
        M = _right_reflection(R, M, bad)


def _word_of(R, M):
    """a reduced word of the Weyl group element M"""
    word = []
    while True:
        i = next((i for i in range(len(M)) if _is_negative(M[i])), None)
        if i is None:
            return tuple(reversed(word))
        # M o s_i: the image of alpha_j is M(s_i alpha_j)
        M = tuple(_apply(M, R.reflect(i, _unit_vector(j, len(M)))) for j in range(len(M)))
        word.append(i)


def in_coordinates(points, simple_roots):
    """rewrite the weights of `points` (simple-root coordinates) in other
    coordinates, given the images of the simple roots
    >>> in_coordinates({"e": ((1,), (-1,))}, [(1, -1)])     # sl_2 in eps-coordinates
    {'e': ((1, -1), (-1, 1))}
    """
    def convert(weight):
        return tuple(sum(c * col[k] for c, col in zip(weight, simple_roots))
                     for k in range(len(simple_roots[0])))

    return {label: tuple(convert(w) for w in weights) for label, weights in points.items()}


@dataclass(frozen=True)
class OrbitDatum(object):
    """a G-orbit with T-fixed points: its base point stabilizer H > T and the
    normal weights there (see homogeneous_fixed_points and assemble)
    >>> from bbcells.core import bb_cells
    >>> closed = OrbitDatum("closed", unipotent_roots=[(1,)], normal=[(-1,)])
    >>> X = assemble("A1", [OrbitDatum("open"), closed])     # P^1 x P^1 > SL_2/T
    >>> closed.normal, bb_cells(X).counts
    ([(-1,)], (1, 2, 1))
    """
    name: str
    generators: tuple = ()
    component_reflections: tuple = ()
    unipotent_roots: tuple = ()
    normal: tuple = ()
    component_elements: tuple = ()
    note: str = ""
    roots: tuple = ()               # wonderful case: the spherical roots I of O_I
    normal_roots: tuple = ()        # the spherical roots of the normal weights, in order
    levi: tuple = ()                # wonderful case: S^p + supp(I)


def assemble(cartan_type, orbits, name=""):
    """FixedPointData of the union of the given orbits (all orbits of X that
    contain T-fixed points), in simple-root coordinates
    >>> X = assemble("A1", [OrbitDatum("open"),
    ...                     OrbitDatum("closed", unipotent_roots=[(1,)], normal=[(-1,)])])
    >>> X.points, X.weights_of("closed:e")                  # P^1 x P^1 > SL_2/T
    (('open:e', 'open:s1', 'closed:e', 'closed:s1'), ((-1,), (-1,)))
    """
    rank = RootSystem(cartan_type).rank
    labels, weights, annotations, dims = [], [], [], set()
    for orbit in orbits:
        points = homogeneous_fixed_points(cartan_type, orbit.generators,
                                          orbit.component_reflections,
                                          orbit.unipotent_roots, orbit.normal,
                                          orbit.component_elements)
        for word, wts in points.items():
            labels.append("%s:%s" % (orbit.name, word))
            weights.append(wts)
            annotation = {"orbit": orbit.name, "word": word}
            if orbit.note:
                annotation["note"] = orbit.note
            if orbit.roots or orbit.normal_roots:
                annotation["roots"] = orbit.roots
                annotation["normal_roots"] = orbit.normal_roots
            annotations.append(annotation)
            dims.add(len(wts))
    if len(dims) != 1:
        raise ValueError("the orbits give tangent spaces of dimensions %s" % sorted(dims))
    return FixedPointData(dims.pop(), rank, tuple(labels), tuple(weights),
                          name=name, annotations=tuple(annotations))


def _support(v):
    return {i for i, c in enumerate(v) if c}


def levi_projection(R, levi, v):
    """the W_L-average of v, i.e. its orthogonal projection onto the
    complement of the roots of the Levi subgroup on `levi`
    >>> levi_projection(RootSystem("A2"), {0}, (0, -2))
    (-1, -2)
    """
    levi = sorted(levi)
    if not levi:
        return tuple(v)
    simple = lambda i: tuple(int(k == i) for k in range(R.rank))
    gram = [[R.inner(simple(i), simple(j)) for j in levi] for i in levi]
    rhs = [R.inner(simple(i), v) for i in levi]
    c = solve(gram, rhs)
    result = [Fraction(x) for x in v]
    for coefficient, i in zip(c, levi):
        result[i] -= coefficient
    if any(x.denominator != 1 for x in result):
        raise ValueError("the W_L-average of %r is not integral" % (v,))
    return tuple(int(x) for x in result)


def invariant_basis(R, levi, reflections, elements):
    """a basis of primitive integer vectors of the subspace of span(Phi_L)
    fixed by the reflections in the given roots and the given Weyl group
    elements. In A_2, s_1 fixes the line of omega_2 = (alpha_1 + 2 alpha_2)/3:
    >>> R = RootSystem("A2")
    >>> invariant_basis(R, {0, 1}, [(1, 0)], []), invariant_basis(R, {0}, [(1, 0)], [])
    ([(1, 2)], [])
    """
    from math import gcd
    levi = sorted(levi)
    if not levi:
        return []
    simple = lambda i: tuple(int(k == i) for k in range(R.rank))
    maps = ([lambda v, b=b: _reflection(R, b, v) for b in reflections] +
            [lambda v, word=word: R.apply_word(word, v) for word in elements])
    rows = []
    for f in maps:
        images = [tuple(x - y for x, y in zip(f(simple(i)), simple(i))) for i in levi]
        rows.extend([image[k] for image in images] for k in range(R.rank))
    basis = null_space(rows, len(levi)) if rows else [
        [int(k == j) for k in range(len(levi))] for j in range(len(levi))]
    result = []
    for vector in basis:
        vector = [Fraction(x) for x in vector]
        denominator = 1
        for x in vector:
            denominator = denominator * x.denominator // gcd(denominator, x.denominator)
        integral = [int(x * denominator) for x in vector]
        g = 0
        for x in integral:
            g = gcd(g, abs(x))
        full = [0] * R.rank
        for x, i in zip(integral, levi):
            full[i] = x // g
        result.append(tuple(full))
    return result


def _invariants_on_levi(R, levi, reflections, elements):
    """dimension of the subspace of span(Phi_L) fixed by W_H (see invariant_basis)"""
    return len(invariant_basis(R, levi, reflections, elements))


BEYOND_R = "normal weights by the W_L-average beyond condition (R)"


def wonderful_orbits(cartan_type, spherical_roots, satellite, parabolic=(), strict=True):
    """OrbitData of a wonderful variety from its spherical roots, S^p
    (`parabolic`, 0-based simple roots) and the satellites: satellite(I) for
    nonempty I c range(len(spherical_roots)) returns None if the satellite
    L_I/H_{L,I} has no T-fixed points, else a dict with keys among
    generators, component_reflections, component_elements, unipotent_roots
    describing H_{L,I} > T inside L_I (L_I = the Levi subgroup on
    S^p + supp(I)). With strict=False, orbits violating condition (R) are
    kept with the W_L-average as normal weights and marked with BEYOND_R;
    the caller must then validate the result (docs/spherical.md, section 7).
    Complete conics (see complete_quadrics), where O12 has no T-fixed points:
    >>> sigma = [(2, 0), (0, 2)]                          # complete conics
    >>> reflections = {(0,): [(1, 0)], (1,): [(0, 1)]}
    >>> sat = lambda I: {"component_reflections": reflections[I]} if len(I) == 1 else None
    >>> orbits = wonderful_orbits("A2", sigma, sat)
    >>> [(o.name, o.normal) for o in orbits]
    [('closed', ((-2, 0), (0, -2))), ('O1', ((-1, -2),)), ('O2', ((-2, -1),))]
    """
    R = RootSystem(cartan_type)
    sigma = [tuple(g) for g in spherical_roots]
    for g in sigma:
        if any(R.coroot_pairing(tuple(int(k == i) for k in range(R.rank)), g)
               for i in parabolic):
            raise ValueError("spherical root %r is not orthogonal to S^p" % (g,))
    orbits = []
    for size in range(len(sigma) + 1):
        for I in combinations(range(len(sigma)), size):
            levi = set(parabolic).union(*(_support(sigma[j]) for j in I))
            if I:
                data = satellite(I)
                if data is None:
                    continue
            else:
                simple = [tuple(int(k == i) for k in range(R.rank)) for i in sorted(levi)]
                data = {"generators": simple}
            phi_l = set(R.positive_roots_of(levi))
            phi_l |= {_negate(b) for b in phi_l}
            generators = [tuple(b) for b in data.get("generators", ())]
            components = [tuple(b) for b in data.get("component_reflections", ())]
            if not all(b in phi_l for b in generators + components):
                raise ValueError("satellite %r: roots outside L_I" % (I,))
            elements = [tuple(word) for word in data.get("component_elements", ())]
            if any(i not in levi for word in elements for i in word):
                raise ValueError("satellite %r: component elements outside W_L" % (I,))
            normal_roots = [j for j in range(len(sigma)) if j not in I]
            note = ""
            if normal_roots and _invariants_on_levi(R, levi, generators + components, elements):
                if strict:
                    raise ValueError("satellite %r: W_H has invariants on the roots of L_I, "
                                     "the normal weights are not determined" % (I,))
                note = BEYOND_R
            unipotent = [b for b in R.positive_roots if b not in phi_l]
            unipotent += [tuple(b) for b in data.get("unipotent_roots", ())]
            normal = [levi_projection(R, levi, _negate(sigma[j])) for j in normal_roots]
            label = "O" + "".join(str(j + 1) for j in I) if I else "closed"
            orbits.append(OrbitDatum(label, tuple(generators), tuple(components),
                                     tuple(unipotent), tuple(normal), tuple(elements), note,
                                     tuple(I), tuple(normal_roots), tuple(sorted(levi))))
    return orbits


def wonderful_variety(cartan_type, spherical_roots, satellite, parabolic=(), name=""):
    """FixedPointData of a wonderful variety (see wonderful_orbits)
    >>> X = wonderful_variety("A1", [(1,)], lambda I: {})    # P^1 x P^1 for SL_2
    >>> X.dim, len(X)
    (2, 4)
    """
    return assemble(cartan_type, wonderful_orbits(cartan_type, spherical_roots, satellite,
                                                  parabolic), name=name)


def orbit_closure(X, roots):
    """the fixed-point data of the closure of the orbit O_K (K = `roots`, indices
    of spherical roots) in a wonderful variety assembled by wonderful_variety:
    the fixed points of the orbits O_J with J c K, without the normal weights
    of the D_gamma with gamma in K
    >>> X = complete_quadrics(3)
    >>> Z = orbit_closure(X, ())                      # the closed orbit G/B
    >>> Z.dim, len(Z)
    (3, 6)
    """
    roots = set(roots)
    points, weights, annotations = [], [], []
    for label, wts in zip(X.points, X.weights):
        a = X.annotation(label)
        if "normal_roots" not in a:
            raise ValueError("the data does not record the orbits of a wonderful variety")
        if not set(a["roots"]) <= roots:
            continue
        normal_roots = a["normal_roots"]
        tangent = wts[:len(wts) - len(normal_roots)]
        kept = [w for j, w in zip(normal_roots, wts[len(wts) - len(normal_roots):])
                if j in roots]
        points.append(label)
        weights.append(tuple(tangent) + tuple(kept))
        annotations.append(dict(a, normal_roots=tuple(j for j in normal_roots if j in roots)))
    dims = {len(w) for w in weights}
    (dim,) = dims
    return FixedPointData(dim, X.rank, tuple(points), tuple(weights),
                          name="orbit closure %s in %s" % (sorted(roots), X.name),
                          annotations=tuple(annotations))


def _runs(indices):
    """maximal runs of consecutive integers
    >>> _runs((0, 1, 3))
    [[0, 1], [3]]
    """
    runs = []
    for i in sorted(indices):
        if runs and runs[-1][-1] == i - 1:
            runs[-1].append(i)
        else:
            runs.append([i])
    return runs


def complete_quadrics(n):
    """complete quadrics in P^{n-1}: the wonderful compactification of
    PGL_n/PO_n, spherical roots 2 alpha_i. Satellites: L_I = S(prod GL_k) over
    the blocks of I, H = S(prod O_k); T-fixed points iff every block has
    k <= 2, and then W_H is generated by the reflections of the blocks
    >>> X = complete_quadrics(3)                             # complete conics
    >>> X.dim, len(X)
    (5, 12)
    """
    if n < 2:
        raise ValueError("need n >= 2")
    r = n - 1
    unit = lambda i: tuple(int(k == i) for k in range(r))

    def satellite(I):
        if any(len(run) > 1 for run in _runs(I)):
            return None                  # a block SL_k/SO_k with k >= 3
        return {"component_reflections": [unit(i) for i in I]}

    sigma = [tuple(2 * c for c in unit(i)) for i in range(r)]
    return wonderful_variety("A%d" % r, sigma, satellite,
                             name="complete quadrics in P^%d" % (n - 1))


def complete_skew_forms(n):
    """complete skew forms on k^{2n}: the wonderful compactification of
    PGL_{2n}/PSp_{2n}, S^p = {alpha_1, alpha_3, ...}, spherical roots
    alpha_{2i-1} + 2 alpha_{2i} + alpha_{2i+1}. Only the closed orbit has
    T-fixed points (Sp_{2k} has full rank in SL_{2k} only for k = 1)
    >>> X = complete_skew_forms(2)                           # P^5 = P(Lambda^2 k^4)
    >>> X.dim, len(X)
    (5, 6)
    """
    if n < 1:
        raise ValueError("need n >= 1")
    r = 2 * n - 1
    sigma = [tuple(1 if k in (2 * i, 2 * i + 2) else 2 if k == 2 * i + 1 else 0
                   for k in range(r)) for i in range(n - 1)]
    return wonderful_variety("A%d" % r, sigma, lambda I: None,
                             parabolic=tuple(range(0, r, 2)),
                             name="complete skew forms on k^%d" % (2 * n))


def _word_from_label(label):
    return () if label == "e" else tuple(int(x[1:]) - 1 for x in label.split("."))


def certify_normal_weights(cartan_type, orbits, trials=3, seed=0):
    """certify the W_L-average normal weights of the orbits marked BEYOND_R.

    For such an orbit the true normal weight of D_gamma at the base point is
    chi = proj(-gamma) + c zeta with c an integer and zeta a primitive vector
    spanning the W_H-invariants in span(Phi_L) (docs/spherical.md, section 3: the
    connected centre of L acts on O(D_gamma) along the component of X^Z
    through x_I and z by -gamma, and chi is W_H-invariant). The
    Atiyah-Bott-Berline-Vergne identity sum_p 1/e_p(lambda) = 0 is evaluated
    exactly at random lambda as a function of c; for |c| > C the terms that
    depend on c are smaller than the rest (an explicit bound), and all
    integers |c| <= C are screened modulo a large prime (an exclusion there
    is an exclusion over Q), for the smallest bound over several lambda and
    then at every sampled lambda. Since the true c is admissible, a single
    admissible value is the true one. Returns ({orbit name: sorted list of
    the admissible c}, [the bounds C found]), or raises if there is more than
    one unknown (a joint search is not implemented) or no bound exists.
    >>> from bbcells.frontends import symmetric
    >>> D = symmetric.diagram("AIII", 2, 3)
    >>> orbits = D.orbits(strict=False)                  # O2 is marked BEYOND_R
    >>> admissible, bounds = certify_normal_weights(D.R.name, orbits)
    >>> admissible
    {'O2': [0]}
    """
    import random
    R = RootSystem(cartan_type)
    rng = random.Random(seed)
    marked = [o for o in orbits if o.note == BEYOND_R]
    unknowns = []
    for o in marked:
        basis = invariant_basis(R, o.levi, list(o.generators) + list(o.component_reflections),
                                o.component_elements)
        if len(basis) != 1 or len(o.normal) != 1:
            raise ValueError("orbit %s: %d invariant directions and %d normal weights; only a "
                             "single unknown is certified" % (o.name, len(basis), len(o.normal)))
        unknowns.append((o, basis[0]))
    if len(unknowns) != 1:
        raise ValueError("%d orbits beyond (R); only a single unknown is certified"
                         % len(unknowns))
    (orbit, zeta), = unknowns
    data = [(o, homogeneous_fixed_points(cartan_type, o.generators, o.component_reflections,
                                         o.unipotent_roots, o.normal, o.component_elements))
            for o in orbits]
    dim = len(data[0][1][next(iter(data[0][1]))]) if data and data[0][1] else 0
    samples, failures = [], 0
    for _ in range(6 * trials):
        if len(samples) >= trials or (failures >= 2 and not samples):
            break                                 # the degeneracy is structural
        lam = [rng.randrange(1, 10 ** 6) for _ in range(R.rank)]
        sample = _abbv_sample(R, data, orbit, zeta, lam)
        # if 1 carries no information (e.g. pairs with e_p' = -e_p cancel for all c),
        # use the moments c_1(TX)^k, k < dim X
        k = 1
        while sample is None and k < min(dim, 5):
            sample = _moment_sample(R, data, orbit, zeta, lam, k)
            k += 1
        if sample is not None:
            samples.append(sample)
        else:
            failures += 1
    if not samples:
        raise ValueError("no usable evaluation point")
    bounds = [s[0] for s in samples]
    bound = min(bounds)
    admissible = set(range(-bound, bound + 1))
    for _, test in samples:
        admissible = {c for c in admissible if test(c)}
    return {orbit.name: sorted(admissible)}, bounds


def satellite_point_count(cartan_type, orbit):
    """|L/H_L|(q) for the satellite of a wonderful orbit with T c H_L, by the
    Brion-Peyre formula (oracles.brion_peyre), independent of normal weights.
    For complete conics the satellite of O1 is PGL_2/PO_2, the nondegenerate
    binary quadratic forms up to scalar (P^2 minus a conic), with q^2 points:
    >>> sigma = [(2, 0), (0, 2)]                          # complete conics
    >>> reflections = {(0,): [(1, 0)], (1,): [(0, 1)]}
    >>> sat = lambda I: {"component_reflections": reflections[I]} if len(I) == 1 else None
    >>> orbits = wonderful_orbits("A2", sigma, sat)
    >>> [satellite_point_count("A2", o) for o in orbits]
    [IntPoly((1,)), IntPoly((0, 0, 1)), IntPoly((0, 0, 1))]
    """
    from bbcells.oracles import brion_peyre, levi_degrees
    R = RootSystem(cartan_type)
    levi = list(orbit.levi)
    if not levi:
        return IntPoly((1,))
    position = {i: k for k, i in enumerate(levi)}
    unit = lambda i: tuple(int(k == i) for k in range(R.rank))

    def matrix(f):
        columns = [f(unit(i)) for i in levi]
        return tuple(tuple(col[levi[r]] for col in columns) for r in range(len(levi)))

    generators = [matrix(lambda v, b=b: _reflection(R, b, v))
                  for b in list(orbit.generators) + list(orbit.component_reflections)]
    generators += [matrix(lambda v, w=w: R.apply_word(w, v)) for w in orbit.component_elements]
    identity = tuple(tuple(int(r == c) for c in range(len(levi))) for r in range(len(levi)))
    group, frontier = {identity}, [identity]
    while frontier:
        new = []
        for M in frontier:
            for S in generators:
                P = tuple(tuple(sum(M[r][k] * S[k][c] for k in range(len(levi)))
                                for c in range(len(levi))) for r in range(len(levi)))
                if P not in group:
                    group.add(P)
                    new.append(P)
        frontier = new
    phi_l = set(R.positive_roots_of(levi))
    phi_l |= {_negate(b) for b in phi_l}
    phi_h = root_subsystem(R, orbit.generators)
    phi_h |= {b for b in orbit.unipotent_roots if b in phi_l}
    dim = len(phi_l) - len(phi_h & phi_l)
    return brion_peyre(sorted(group), dim, levi_degrees(R.cartan, set(levi)))


def orbit_count_check(cartan_type, orbits, X, rank):
    """compare, for every orbit O_I with T-fixed points, the point count from
    the BB cells (Moebius inversion over the orbit closures X^J, J c I) with
    |G/P_{S_I}|(q) |L/H_L|(q) (Brion-Peyre). Returns {orbit: (bb, expected)}.
    For complete conics: the closed orbit is the flag variety of k^3, O1 a
    bundle over P^2 with fibre PGL_2/PO_2:
    >>> sigma = [(2, 0), (0, 2)]                          # complete conics
    >>> reflections = {(0,): [(1, 0)], (1,): [(0, 1)]}
    >>> sat = lambda I: {"component_reflections": reflections[I]} if len(I) == 1 else None
    >>> orbits = wonderful_orbits("A2", sigma, sat)
    >>> counts = orbit_count_check("A2", orbits, complete_quadrics(3), 2)
    >>> counts["closed"]
    (IntPoly((1, 2, 2, 1)), IntPoly((1, 2, 2, 1)))
    >>> counts["O1"]
    (IntPoly((0, 0, 1, 1, 1)), IntPoly((0, 0, 1, 1, 1)))
    """
    from bbcells.core import bb_cells
    from bbcells.oracles import from_degrees, levi_degrees
    R = RootSystem(cartan_type)
    closures = {}

    def closure_count(J):
        if J not in closures:
            closures[J] = IntPoly.from_counts(bb_cells(orbit_closure(X, J)).counts)
        return closures[J]

    result = {}
    for orbit in orbits:
        I = tuple(orbit.roots)
        bb = IntPoly(())
        for size in range(len(I) + 1):
            for J in combinations(I, size):
                term = closure_count(tuple(J))
                bb = bb + term if (len(I) - size) % 2 == 0 else bb - term
        flag = from_degrees(R.degrees, levi_degrees(R.cartan, set(orbit.levi)))
        result[orbit.name] = (bb, flag * satellite_point_count(cartan_type, orbit))
    return result


def _open_term(d, m):
    """the coefficients of q^d (q - 1)^m, lowest degree first"""
    from math import comb
    return [0] * d + [comb(m, k) * (-1) ** (m - k) for k in range(m + 1)]


def open_orbit_count(X, cocharacter):
    """the point count (E-polynomial) of the open orbit O_J of a wonderful
    variety, or of an orbit closure X = X^J, from its fixed points alone:
        |O_J|(q) = sum of q^d (q - 1)^m
    over the fixed points x in the orbits O_I, I c J, at which all m = |J - I|
    normal weights are lambda-positive, d being the number of lambda-positive
    tangent weights of O_I at x. The plus-cell of such an x meets O_J in
    A^d x G_m^m, the others miss O_J (docs/spherical.md section 7).
    The cocharacter must be generic.
    >>> X = complete_quadrics(3)                        # complete conics
    >>> print(open_orbit_count(X, (1, 3)).format("q"))  # smooth conics
    -q^2 + q^5
    >>> print(open_orbit_count(orbit_closure(X, (0,)), (1, 3)).format("q"))
    q^2 + q^3 + q^4
    """
    counts = []
    for label, weights in zip(X.points, X.weights):
        values = [sum(a * b for a, b in zip(w, cocharacter)) for w in weights]
        if 0 in values:
            raise ValueError("the cocharacter is not generic at %s" % label)
        m = len(X.annotation(label)["normal_roots"])
        tangent, normal = values[:len(values) - m], values[len(values) - m:]
        if all(v > 0 for v in normal):
            term = _open_term(sum(v > 0 for v in tangent), m)
            counts += [0] * (len(term) - len(counts))
            for k, c in enumerate(term):
                counts[k] += c
    return IntPoly(tuple(counts))


def _sum_sign(terms):
    """the sign (-1, 0, 1) of a sum of Fractions, proved: exact zero by
    cancelling equal and opposite terms, a nonzero sign by 150-digit decimal
    arithmetic with an error bound; None if neither succeeds"""
    from collections import Counter
    from decimal import Decimal, localcontext
    counts = Counter(terms)
    rest = []
    for t, k in counts.items():
        if t > 0:
            k -= counts.get(-t, 0)
            rest.extend([t] * max(k, 0) + [-t] * max(-k, 0))
    if not rest:
        return 0
    if len(rest) <= 200:
        total = sum(rest, Fraction(0))
        return (total > 0) - (total < 0)
    with localcontext() as context:
        context.prec = 150
        values = [Decimal(t.numerator) / Decimal(t.denominator) for t in rest]
        total = sum(values, Decimal(0))
        error = len(values) * max(abs(v) for v in values) * Decimal(10) ** -140
        if abs(total) <= error:
            return None
        return 1 if total > 0 else -1


def _abbv_sample(R, data, orbit, zeta, lam, max_order=4):
    """one evaluation point of the ABBV identity sum_p 1/e_p(lambda) = 0, as a
    function g(c) = K + sum_v 1/(A_v (a_v + b_v c)) of the unknown shift.
    Expanding g(c) = K + sum_k (-1)^(k-1) S_k / c^k (S_k = sum a^(k-1)/(A b^k)),
    let m be the first order with a provably nonzero coefficient; then for
    |c| >= C, |c^m g(c)| >= |S_m| - sum |a|^m / (|A| |b|^m (|b| |c| - |a|)) > 0.
    Returns (C, test) with test(c) = False only if g(c) != 0 (checked modulo a
    prime), or None if lambda is unusable."""
    from math import exp, log
    P = (1 << 61) - 1
    pair = lambda w: sum(a * b for a, b in zip(w, lam))
    denominators, varying = [], []
    for o, points in data:
        for label, weights in points.items():
            values = [pair(w) for w in weights]
            if o is orbit:
                A = 1
                for v in values[:-1]:
                    A *= v
                a, b = values[-1], pair(R.apply_word(_word_from_label(label), zeta))
                if b == 0:
                    denominators.append(A * a)
                else:
                    varying.append((A, a, b))
            else:
                e = 1
                for v in values:
                    e *= v
                denominators.append(e)
    if not varying or any(d == 0 or d % P == 0 for d in denominators):
        return None
    if any(A == 0 or A % P == 0 or b % P == 0 for A, a, b in varying):
        return None
    coefficients = [[Fraction(1, d) for d in denominators]]
    coefficients += [[Fraction(a ** (k - 1), A * b ** k) for A, a, b in varying]
                     for k in range(1, max_order + 1)]
    order, leading = None, None
    for m, terms in enumerate(coefficients):
        sign = _sum_sign(terms)
        if sign is None:
            return None                       # cannot decide; try another lambda
        if sign != 0:
            order = m
            break
    if order is None:
        return None
    from decimal import Decimal, localcontext
    with localcontext() as context:
        context.prec = 150
        leading = abs(sum((Decimal(t.numerator) / Decimal(t.denominator)
                           for t in coefficients[order]), Decimal(0)))
        log_leading = float(leading.ln()) - 1e-9
    C = max(abs(Fraction(a, b)) for A, a, b in varying) + 1

    def tail(C):          # bound for |c^m g(c) - (+-S_m)| / |S_m| at |c| >= C
        return sum(exp(order * (log(abs(a)) - log(abs(b))) - log(abs(A))
                       - log(abs(b) * C - abs(a)) - log_leading) if a else 0.0
                   for A, a, b in varying)

    while tail(C) >= 0.5:                     # the margin 1/2 absorbs rounding
        C *= 2
        if C > 10 ** 5:                        # too large to screen
            return None
    constant_mod = 0
    for d in denominators:
        constant_mod = (constant_mod + pow(d % P, P - 2, P)) % P
    terms_mod = [(A % P, a % P, b % P) for A, a, b in varying]

    def test(c):
        total = constant_mod
        for A, a, b in terms_mod:
            d = A * ((a + b * c) % P) % P
            if d == 0:
                return True                    # cannot exclude c this way
            total = (total + pow(d, P - 2, P)) % P
        return total == 0

    return int(C) + 1, test


def _restrict(orbits, J, *unknowns):
    """the orbits of the closure X^J with the normal weights of the directions
    in J; for each unknown (name, gamma) the orbit is marked BEYOND_R and its
    normal weight in the direction gamma is put last, all other notes are
    cleared"""
    from dataclasses import replace
    unknown = dict(unknowns)
    restricted = []
    for o in orbits:
        if not set(o.roots) <= J:
            continue
        keep = [k for k, g in enumerate(o.normal_roots) if g in J]
        note = ""
        if o.name in unknown:
            keep.sort(key=lambda k: o.normal_roots[k] == unknown[o.name])
            note = BEYOND_R
        restricted.append(replace(o, normal=tuple(o.normal[k] for k in keep),
                                  normal_roots=tuple(o.normal_roots[k] for k in keep),
                                  note=note))
    return restricted


def opposition(R):
    """the opposition involution epsilon = -w_0, as a map on vectors in
    simple-root coordinates
    >>> eps = opposition(RootSystem("A3"))
    >>> eps((1, 0, 0)), eps((1, 2, 3))
    ((0, 0, 1), (3, 2, 1))
    """
    total = [0] * R.rank
    for b in R.positive_roots:
        total = [x + y for x, y in zip(total, b)]
    word, v = [], tuple(total)
    while True:
        i = next((i for i in range(R.rank) if _pairing(R, v, i) > 0), None)
        if i is None:
            break
        v = R.reflect(i, v)
        word.append(i)
    return lambda v: tuple(-x for x in R.apply_word(word, tuple(v)))


def _pairing(R, v, i):
    """<v, alpha_i^vee> for v in simple-root coordinates"""
    return sum(b * R.cartan[i][j] for j, b in enumerate(v))


def _dominant_in(R, v, levi):
    """the representative of W_L v that is dominant for the simple roots in levi"""
    v = tuple(v)
    while True:
        i = next((i for i in levi if _pairing(R, v, i) < 0), None)
        if i is None:
            return v
        v = R.reflect(i, v)


def certify_by_symmetry(cartan_type, orbits, spherical_roots):
    """decide unknown normal weights beyond (R) by the opposition symmetry
    (docs/spherical.md section 7; paper, Theorem "opposition").

    If the open orbit has T-fixed points, its stabilizer is G^{Ad t} (up to
    normalizer) with t in T, so the Chevalley involution C_0 pinned to (T, B)
    preserves it; w_0 composed with C_0 is then an automorphism of X,
    twisted by an automorphism of G that preserves T and B and acts on
    characters by epsilon = -w_0. For an unknown (K, gamma), chi_gamma =
    pr(-gamma) + c zeta, with epsilon fixing gamma, K and S_K, it maps x_K
    to a point u x_K with u in W_{L_K}, whence epsilon(chi_gamma) =
    u(chi_gamma) and c (epsilon(zeta) - u(zeta)) = 0. So c = 0 whenever
    epsilon(zeta) is not in W_{L_K} zeta. Returns {(orbit, gamma): [0]} for
    the unknowns decided this way (gamma an index into spherical_roots).
    >>> from bbcells.frontends import symmetric
    >>> D = symmetric.diagram("AIII", 2, 3)
    >>> certify_by_symmetry(D.R.name, D.orbits(strict=False), D.spherical_roots)
    {('O2', 0): [0]}
    """
    R = RootSystem(cartan_type)
    Sigma = [tuple(g) for g in spherical_roots]
    if not any(len(o.roots) == len(Sigma) for o in orbits):
        return {}                       # the open orbit has no T-fixed points
    eps = opposition(R)
    unit = lambda i: tuple(int(k == i) for k in range(R.rank))
    image = {i: next(k for k in range(R.rank) if eps(unit(i)) == unit(k))
             for i in range(R.rank)}
    result = {}
    for o in orbits:
        if o.note != BEYOND_R:
            continue
        basis = invariant_basis(R, o.levi, list(o.generators) + list(o.component_reflections),
                                o.component_elements)
        if len(basis) != 1:
            continue
        zeta, levi = basis[0], sorted(o.levi)
        K = {Sigma[i] for i in o.roots}
        if {image[i] for i in levi} != set(levi) or {eps(g) for g in K} != K:
            continue
        if _dominant_in(R, eps(zeta), levi) == _dominant_in(R, zeta, levi):
            continue
        for g in o.normal_roots:
            if eps(Sigma[g]) == Sigma[g]:
                result[(o.name, g)] = [0]
    return result


def certify_by_closures(cartan_type, orbits, trials=3, seed=0, methods=None):
    """certify all normal weights beyond (R) one at a time, on orbit closures.

    The closure X^J of O_J is a smooth wonderful variety whose orbits are the
    O_K, K c J, with the normal weights of the D_gamma, gamma in J - K. An
    unknown (K, gamma), i.e. the normal weight of D_gamma on the marked orbit
    O_K, is decided on a closure X^J, J > K + gamma, in which every other
    normal weight is proved (condition (R)) or certified before:
      * by certify_by_point_count on the smallest such J that bounds the
        unknown (against the E-polynomial if the open orbit O_J has T-fixed
        points, else by Poincare duality, which can leave c unbounded);
      * if no unknown can be decided so, pairs of unknowns on different
        orbits are decided jointly by the point count on the smallest
        closure containing both;
      * failing that, on X^{K + gamma} by certify_normal_weights (ABBV).
    This is repeated until no unknown is left. Returns
    {(orbit, gamma): admissible c}; `methods`, if a dict, receives
    {(orbit, gamma): (method, J)}. Values are used as certified only if they
    are [0], so later steps assume c = 0 for the earlier ones.
    >>> from bbcells.frontends import symmetric
    >>> D = symmetric.diagram("AIII", 2, 3)
    >>> orbits = D.orbits(strict=False)                  # O2 is marked BEYOND_R
    >>> certify_by_closures(D.R.name, orbits)
    {('O2', 0): [0]}
    """
    names = {o.name for o in orbits}
    marked = {o.name for o in orbits if o.note == BEYOND_R}
    with_points = {frozenset(o.roots) for o in orbits}
    everything = set()
    for o in orbits:
        everything |= set(o.roots) | set(o.normal_roots)
    pending = sorted((o.name, g) for o in orbits if o.name in marked for g in o.normal_roots)
    roots_of = {o.name: set(o.roots) for o in orbits}
    result = {}

    def others_known(J, unknowns):
        return all((o.name, g) in result or (o.name, g) in unknowns
                   for o in orbits if o.name in marked and roots_of[o.name] <= J
                   for g in o.normal_roots if g in J)

    def closures(unknowns):
        """the closures on which the unknowns can be decided, smallest first,
        an open orbit with fixed points (E-polynomial) first within a size"""
        base = set()
        for name, gamma in unknowns:
            base |= roots_of[name] | {gamma}
        rest = sorted(everything - base)
        for size in range(len(rest) + 1):
            candidates = [base | set(extra) for extra in combinations(rest, size)]
            candidates = [J for J in candidates if others_known(J, unknowns)]
            candidates.sort(key=lambda J: frozenset(J) not in with_points)
            for J in candidates:
                yield J

    def by_point_count(unknowns):
        """(admissible, J) from the first closure that bounds the unknowns"""
        for J in closures(unknowns):
            try:
                admissible, _ = certify_by_point_count(
                    cartan_type, _restrict(orbits, J, *unknowns), trials, seed)
            except ValueError as error:
                if not any(text in str(error) for text in ("unbounded", "too large")):
                    raise
                continue
            return admissible, J
        return None

    def record(unknowns, admissible, method, J):
        for name, gamma in unknowns:
            result[(name, gamma)] = admissible[name]
            if methods is not None:
                methods[(name, gamma)] = (method, tuple(sorted(J)))

    while pending:
        progress = []
        for unknown in pending:
            found = by_point_count([unknown])
            if found is not None:
                record([unknown], found[0], "point count", found[1])
                progress.append(unknown)
        if not progress:
            for first, second in combinations(pending, 2):
                if first[0] == second[0]:
                    continue
                found = by_point_count([first, second])
                if found is not None:
                    record([first, second], found[0], "joint point count", found[1])
                    progress = [first, second]
                    break
        if not progress:
            for unknown in pending:
                name, gamma = unknown
                base = roots_of[name] | {gamma}
                if not others_known(base, [unknown]):
                    continue
                try:
                    admissible, _ = certify_normal_weights(
                        cartan_type, _restrict(orbits, base, unknown), trials, seed)
                except ValueError as error:
                    if "no usable evaluation point" not in str(error):
                        raise
                else:
                    record([unknown], admissible, "ABBV", base)
                    progress = [unknown]
                    break
        if not progress:
            raise ValueError("no usable evaluation point for %s" % pending)
        pending = [u for u in pending if u not in progress]
    assert names >= {name for name, _ in result}
    return result


def _lattice_shift(normal, zeta):
    """c0 in [0, 1) with {c : normal + c zeta integral} = c0 + Z (zeta primitive),
    or None if that set is empty"""
    # u with u.zeta = 1 by the extended Euclidean algorithm on the entries
    g, u = 0, [0] * len(zeta)
    for i, z in enumerate(zeta):
        if z == 0:
            continue
        if g == 0:
            g, u = abs(z), [0] * len(zeta)
            u[i] = 1 if z > 0 else -1
            continue
        # combine g = u.zeta with z: x g + y z = gcd(g, z)
        a, b, x0, x1, y0, y1 = g, z, 1, 0, 0, 1
        while b:
            q = a // b
            a, b, x0, x1, y0, y1 = b, a - q * b, x1, x0 - q * x1, y1, y0 - q * y1
        if a < 0:
            a, x0, y0 = -a, -x0, -y0
        u = [x0 * v for v in u]
        u[i] += y0
        g = a
    if g != 1:
        raise ValueError("zeta is not primitive")
    c0 = -sum(Fraction(a) * b for a, b in zip(normal, u))
    c0 -= c0.numerator // c0.denominator
    if any((Fraction(a) + c0 * b).denominator != 1 for a, b in zip(normal, zeta)):
        return None
    return c0


def certify_by_point_count(cartan_type, orbits, trials=3, seed=0):
    """certify the unknown normal weights of the orbits marked BEYOND_R (one
    or two orbits; each unknown is the last normal weight of its orbit) by the
    point count of the variety assembled from `orbits` (an orbit closure X^J).

    With chi = normal + c zeta (normal the W_L-average, as in
    certify_normal_weights), the unknown weight at the fixed point w x of a
    marked orbit pairs with lambda to a_w + c b_w, with a_w = <w(normal),
    lambda> and b_w = <w(zeta), lambda>. Every count below is therefore of the
    form P_0 + sum_i F_i(c_i), each F_i constant between the thresholds
    -a_w / b_w of its orbit, and for the true c and lambda generic for it
    the count is that of the variety:
      * if O_J has T-fixed points, the count of O_J from the fixed points
        (open_orbit_count) must equal |G/P_{S_J}|(q) |L/H_L|(q) (Brion-Peyre);
      * otherwise the BB count of X^J must be palindromic (Poincare duality;
        the condition v - reverse(v) = 0, linear in the counts like the first).
    The boxes of intervals that satisfy the condition are found by matching
    F_1 against the target minus F_2. The thresholds of each unknown are
    checked to be disjoint across the samples, so for the true c at most one
    sample per unknown is not generic; with more samples than unknowns some
    sample decides. The weights lie in the root lattice (G adjoint), so c_i
    is in c0_i + Z. Returns ({orbit name: sorted list of the admissible c_i},
    the admissible tuples); raises if an admissible box is unbounded.
    >>> from bbcells.frontends import symmetric
    >>> D = symmetric.diagram("AIII", 2, 3)
    >>> orbits = D.orbits(strict=False)                  # O2 is marked BEYOND_R
    >>> certify_by_point_count(D.R.name, orbits)
    ({'O2': [0]}, [(0,)])
    """
    import random
    from math import ceil, floor
    from itertools import product
    from bbcells.oracles import from_degrees, levi_degrees
    R = RootSystem(cartan_type)
    rng = random.Random(seed)
    marked = [o for o in orbits if o.note == BEYOND_R]
    if not 1 <= len(marked) <= 2 or not all(o.normal for o in marked):
        raise ValueError("one or two orbits with an unknown normal weight (the last) "
                         "are required")
    trials = max(trials, len(marked) + 1)
    zetas, shifts = [], []
    for o in marked:
        basis = invariant_basis(R, o.levi, list(o.generators) + list(o.component_reflections),
                                o.component_elements)
        if len(basis) != 1:
            raise ValueError("orbit %s: %d invariant directions" % (o.name, len(basis)))
        c0 = _lattice_shift(o.normal[-1], basis[0])
        if c0 is None:
            raise ValueError("no c puts the normal weight of %s in the root lattice" % o.name)
        zetas.append(basis[0])
        shifts.append(c0)
    J = set()
    for o in orbits:
        J |= set(o.roots) | set(o.normal_roots)
    top = [o for o in orbits if set(o.roots) == J]
    X = assemble(cartan_type, orbits)
    grouped = {}
    for label, weights in zip(X.points, X.weights):
        a = X.annotation(label)
        grouped.setdefault(a["orbit"], {})[a["word"]] = weights
    data = [(o, grouped.get(o.name, {})) for o in orbits]
    dim = len(X.weights[0])
    length = dim + 2
    if top:
        flag = from_degrees(R.degrees, levi_degrees(R.cartan, set(top[0].levi)))
        expected = flag * satellite_point_count(cartan_type, top[0])
        target = list(expected.coefficients) + [0] * (length - len(expected.coefficients))
        if len(target) > length:
            raise ValueError("the E-polynomial has too high a degree")
        condition = lambda v: tuple(v)

        def term(d, normal):
            """the count of the plus-cell in O_J: q^d (q - 1)^m or 0"""
            v = [0] * length
            if all(normal):
                for k, c in enumerate(_open_term(d, len(normal))):
                    v[k] += c
            return v
    else:
        target = [0] * length
        # v -> v - reverse(v) on degrees 0..dim (the last slot must stay empty)
        condition = lambda v: tuple(v[d] - v[dim - d] for d in range(dim + 1)) + (v[dim + 1],)

        def term(d, normal):
            """the BB cell: q^(d + number of positive normal weights)"""
            v = [0] * length
            v[d + sum(normal)] += 1
            return v
    target = condition(target)
    add = lambda u, v, sign=1: [x + sign * y for x, y in zip(u, v)]
    samples, seen = [], [set() for _ in marked]
    attempts = 0
    while len(samples) < trials:
        attempts += 1
        if attempts > 20 * trials:
            raise ValueError("no generic cocharacters found")
        lam = [rng.randrange(1, 10 ** 9) for _ in range(R.rank)]
        pair = lambda w: sum(a * b for a, b in zip(w, lam))
        counts = [0] * length                  # every unknown at -infinity
        moving = [[] for _ in marked]          # (threshold, change of the count)
        generic = True
        for o, points in data:
            i = next((k for k, m in enumerate(marked) if m is o), None)
            m = len(o.normal)
            for label, weights in points.items():
                values = [pair(w) for w in weights]
                tangent, normal = values[:len(values) - m], values[len(values) - m:]
                if i is None:
                    a, b = None, 0
                else:
                    normal, a = normal[:-1], normal[-1]
                    b = pair(R.apply_word(_word_from_label(label), zetas[i]))
                if any(v == 0 for v in tangent + normal) or (a == 0 and b == 0):
                    generic = False
                    break
                d = sum(v > 0 for v in tangent)
                normal = [v > 0 for v in normal]
                if a is None:
                    counts = add(counts, term(d, normal))
                elif b == 0:
                    counts = add(counts, term(d, normal + [a > 0]))
                else:
                    below, above = term(d, normal + [False]), term(d, normal + [True])
                    # at c -> -infinity the weight a + c b is positive iff b < 0
                    if b < 0:
                        below, above = above, below
                    counts = add(counts, below)
                    moving[i].append((Fraction(-a, b), add(above, below, -1)))
            if not generic:
                break
        if not generic:
            continue
        thresholds = [{t for t, _ in m} for m in moving]
        if any(t & old for t, old in zip(thresholds, seen)):
            continue
        # the piecewise constant F_i: intervals and their (cumulative) values
        pieces = []
        for m in moving:
            m.sort(key=lambda entry: entry[0])
            delta, low, k, piece = [0] * length, None, 0, []
            while True:
                high = m[k][0] if k < len(m) else None
                piece.append(((low, high), condition(delta)))
                if high is None:
                    break
                while k < len(m) and m[k][0] == high:
                    delta = add(delta, m[k][1])
                    k += 1
                low = high
            pieces.append(piece)
        rest = tuple(t - c for t, c in zip(target, condition(counts)))
        if len(marked) == 1:
            boxes = [(interval,) for interval, value in pieces[0] if value == rest]
        else:
            lookup = {}
            for interval, value in pieces[1]:
                lookup.setdefault(value, []).append(interval)
            boxes = [(interval, other) for interval, value in pieces[0]
                     for other in lookup.get(tuple(r - v for r, v in zip(rest, value)), ())]
        samples.append((thresholds, boxes))
        for old, t in zip(seen, thresholds):
            old |= t

    def inside(c, thresholds, boxes):
        if any(x in t for x, t in zip(c, thresholds)):
            return True                            # lambda is not generic for c
        return any(all((lo is None or lo < x) and (hi is None or x < hi)
                       for x, (lo, hi) in zip(c, box)) for box in boxes)

    # the true c is in a box of every sample that is generic for it, and some is
    candidates = set()
    for _, boxes in samples:
        for box in boxes:
            if any(lo is None or hi is None for lo, hi in box):
                raise ValueError("the point count admits unbounded c")
            ranges = [[c0 + k for k in range(ceil(lo - c0), floor(hi - c0) + 1)]
                      for (lo, hi), c0 in zip(box, shifts)]
            size = 1
            for r in ranges:
                size *= len(r)
            if size > 10 ** 6:
                raise ValueError("an admissible box is too large")
            candidates.update(product(*ranges))
    admissible = sorted(c for c in candidates if all(inside(c, t, b) for t, b in samples))
    clean = lambda x: int(x) if x.denominator == 1 else x
    admissible = [tuple(clean(x) for x in c) for c in admissible]
    return ({o.name: sorted({c[i] for c in admissible}) for i, o in enumerate(marked)},
            admissible)


def _moment_sample(R, data, orbit, zeta, lam, k):
    """the ABBV identity for the class c_1(TX)^k (k < dim X):
    I(c) = sum_p (S_p + b_p c)^k / (A_p (a_p + b_p c)) + (fixed terms) = 0.
    Division gives I(c) = P(c) + sum_v (S_v - a_v)^k / (A_v (a_v + b_v c)), with
    P a polynomial whose coefficients are exact sums; if P is provably nonzero
    of degree d, then for |c| >= C, |P(c)| >= |p_d| |c|^d / 2 exceeds the
    remainder. Returns (C, test) like _abbv_sample, or None."""
    from decimal import Decimal, localcontext
    P_ = (1 << 61) - 1
    pair = lambda w: sum(a * b for a, b in zip(w, lam))
    fixed, varying = [], []
    for o, points in data:
        for label, weights in points.items():
            values = [pair(w) for w in weights]
            total = sum(values)
            if o is orbit:
                A = 1
                for v in values[:-1]:
                    A *= v
                a, b = values[-1], pair(R.apply_word(_word_from_label(label), zeta))
                if b == 0:
                    fixed.append((Fraction(total) ** k, A * a))
                else:
                    varying.append((A, a, b, total))
            else:
                e = 1
                for v in values:
                    e *= v
                fixed.append((Fraction(total) ** k, e))
    if not varying or any(e == 0 or e % P_ == 0 for _, e in fixed):
        return None
    if any(A == 0 or A % P_ == 0 or b % P_ == 0 for A, a, b, S in varying):
        return None
    # (S + b c)^k = (a + b c) Q(c) + (S - a)^k: Q by synthetic division in c
    coefficient_terms = [[] for _ in range(max(k, 1))]      # coefficient of c^j in P
    for numerator, e in fixed:
        coefficient_terms[0].append(Fraction(numerator) / e)
    remainders = []
    from math import comb
    for A, a, b, S in varying:
        poly = [Fraction(comb(k, j) * S ** (k - j) * b ** j) for j in range(k + 1)]
        quotient = [Fraction(0)] * k                           # degree k - 1
        rest = poly[:]
        for j in range(k, 0, -1):                              # divide by (b c + a)
            q = rest[j] / b
            quotient[j - 1] = q
            rest[j] -= q * b
            rest[j - 1] -= q * a
        for j, q in enumerate(quotient):
            if q:
                coefficient_terms[j].append(q / A)
        remainders.append((A, a, b, rest[0]))                  # rest[0] = (S - a)^k
    signs = [_sum_sign(terms) for terms in coefficient_terms]
    if any(s is None for s in signs):
        return None
    nonzero = [j for j, s in enumerate(signs) if s]
    if not nonzero:
        return None
    d = max(nonzero)
    with localcontext() as context:
        context.prec = 150
        dec = lambda x: Decimal(x.numerator) / Decimal(x.denominator)
        coefficients = [abs(sum((dec(t) for t in terms), Decimal(0)))
                        for terms in coefficient_terms]
        lead = coefficients[d]

        def lower(C):              # |P(c)| >= |c|^d (lead - sum_{j<d} |p_j| / C^(d-j))
            return C ** d * (lead - sum(coefficients[j] / C ** (d - j) for j in range(d)))

        def remainder(C):
            return sum(abs(dec(Fraction(r))) / (abs(dec(Fraction(A))) *
                                                (abs(b) * C - abs(a)))
                       for A, a, b, r in remainders if r)

        C = Decimal(int(max(abs(Fraction(a, b)) for A, a, b, r in remainders)) + 2)
        while lower(C) <= 2 * remainder(C) or lower(C) <= 0:
            C *= 2
            if C > 10 ** 5:                    # too large to screen
                return None
    fixed_mod = 0
    for numerator, e in fixed:
        n = Fraction(numerator)
        fixed_mod = (fixed_mod + n.numerator % P_ * pow(n.denominator * e % P_, P_ - 2, P_)) % P_
    terms_mod = [(A % P_, a % P_, b % P_, S % P_) for A, a, b, S in varying]

    def test(c):
        total = fixed_mod
        for A, a, b, S in terms_mod:
            den = A * ((a + b * c) % P_) % P_
            if den == 0:
                return True
            total = (total + pow((S + b * c) % P_, k, P_) * pow(den, P_ - 2, P_)) % P_
        return total == 0

    return int(C) + 1, test


def stream_cell_counts(cartan_type, orbits, lam, progress=None, processes=1):
    """the BB cell counts c_d of the variety assembled from `orbits`, for the
    cocharacter lam, without storing fixed points: every orbit's cosets are
    enumerated level by level (coset_representatives' search, keeping one
    length level of inverse permutations as bytes), and each representative
    contributes the number of lam-positive weights among w(Phi - Phi_H) and
    w(N). Raises if lam is not generic. When W_H is not generated by
    reflections, the search runs over cosets of the reflection part and every
    count is divided by |W_H : W_refl|. With processes > 1 the orbits are
    counted in parallel (multiprocessing). Complete conics:
    >>> sigma = [(2, 0), (0, 2)]                          # complete conics
    >>> reflections = {(0,): [(1, 0)], (1,): [(0, 1)]}
    >>> sat = lambda I: {"component_reflections": reflections[I]} if len(I) == 1 else None
    >>> orbits = wonderful_orbits("A2", sigma, sat)
    >>> stream_cell_counts("A2", orbits, (1, 5))
    (1, 2, 3, 3, 2, 1)
    >>> stream_cell_counts("A2", orbits, (1, 5), processes=2)
    (1, 2, 3, 3, 2, 1)
    """
    return stream_cell_counts_many(cartan_type, orbits, [lam], progress, processes)[0]


def stream_cell_counts_many(cartan_type, orbits, lams, progress=None, processes=1):
    """stream_cell_counts for several cocharacters, with all (orbit,
    cocharacter) pairs counted in one pool of processes if processes > 1
    >>> sigma = [(2, 0), (0, 2)]                          # complete conics
    >>> reflections = {(0,): [(1, 0)], (1,): [(0, 1)]}
    >>> sat = lambda I: {"component_reflections": reflections[I]} if len(I) == 1 else None
    >>> stream_cell_counts_many("A2", wonderful_orbits("A2", sigma, sat), [(1, 5), (7, 2)])
    [(1, 2, 3, 3, 2, 1), (1, 2, 3, 3, 2, 1)]
    """
    jobs = [(cartan_type, orbit, tuple(lam)) for lam in lams for orbit in orbits]
    if processes > 1 and len(jobs) > 1:
        import multiprocessing
        with multiprocessing.Pool(min(processes, len(jobs))) as pool:
            results = pool.starmap(_stream_orbit, jobs)
    else:
        results = [_stream_orbit(*job) for job in jobs]
    answers = []
    for k in range(len(lams)):
        counts = {}
        for orbit, (orbit_counts, number) in zip(orbits, results[k * len(orbits):]):
            for d, c in orbit_counts.items():
                counts[d] = counts.get(d, 0) + c
            if progress:
                progress(orbit.name, number)
        top = max(counts)
        answers.append(tuple(counts.get(d, 0) for d in range(top + 1)))
    return answers


def _stream_orbit(cartan_type, orbit, lam):
    """({d: number of fixed points of the orbit with d lam-positive weights},
    number of fixed points) for stream_cell_counts"""
    R = RootSystem(cartan_type)
    roots, index, simple, positive = _root_table(R)
    n = len(roots)
    if n > 255:
        raise ValueError("more than 255 roots")
    pair = lambda w: sum(a * b for a, b in zip(w, lam))
    root_sign = [pair(b) for b in roots]
    if any(v == 0 for v in root_sign):
        raise ValueError("lam is orthogonal to a root")
    root_positive = bytes(1 if v > 0 else 0 for v in root_sign)
    simple_index = [index[_unit_vector(i, R.rank)] for i in range(R.rank)]
    simple_bytes = [bytes(s) for s in simple]
    orbit_counts = {}
    phi_sym = root_subsystem(R, orbit.generators)
    reflections = sorted(phi_sym) + [tuple(b) for b in orbit.component_reflections]
    phi_h, frontier = set(phi_sym), [tuple(b) for b in orbit.unipotent_roots]
    while frontier:
        beta = frontier.pop()
        if beta in phi_h:
            continue
        phi_h.add(beta)
        frontier.extend(_reflection(R, s, beta) for s in reflections)
    complement = [index[b] for b in roots if b not in phi_h]
    normal = [tuple(v) for v in orbit.normal]
    in_h = frozenset(index[b] for b in root_subsystem(R, reflections)
                     if b in set(R.positive_roots))
    level = {bytes(range(n))}
    total = 0
    while level:
        new = set()
        for v in level:
            w = bytearray(n)                           # w from w^{-1}
            for k, image in enumerate(v):
                w[image] = k
            d = sum(root_positive[w[k]] for k in complement)
            if normal:
                columns = [roots[w[k]] for k in simple_index]  # w(alpha_i)
                for nu in normal:
                    value = sum(c * pair(col) for c, col in zip(nu, columns) if c)
                    if value == 0:
                        raise ValueError("lam is not generic for %s" % orbit.name)
                    d += value > 0
            orbit_counts[d] = orbit_counts.get(d, 0) + 1
            total += 1
            for i in range(R.rank):
                image = v[simple_index[i]]
                if image not in positive or image in in_h:
                    continue
                new.add(bytes(v[k] for k in simple_bytes[i]))
        level = new
    # every fixed point w.x is met once for each coset of W_refl in W_H
    multiplicity = 1
    if orbit.component_elements:
        multiplicity = _component_group_order(R, reflections, orbit.component_elements)
    for d, k in orbit_counts.items():
        if k % multiplicity:
            raise AssertionError("coset counts not divisible by |W_H : W_refl|")
    return {d: k // multiplicity for d, k in orbit_counts.items()}, total // multiplicity


def _component_group_order(R, reflections, words):
    """|W_H : W_refl| for W_H generated by W_refl and the given elements: the
    size of the orbit of the identity coset under right multiplication"""
    roots, index, simple, positive = _root_table(R)
    positive_h = [b for b in root_subsystem(R, reflections) if b in set(R.positive_roots)]
    h_indices = [index[b] for b in positive_h]
    reflection = {b: tuple(index[_reflection(R, b, c)] for c in roots) for b in positive_h}
    identity = tuple(range(len(roots)))
    glue = []
    for word in words:
        C = identity
        for i in reversed(word):
            C = tuple(simple[i][k] for k in C)
        glue.append(C)

    def reduce(u):
        while True:
            bad = next((b for b, k in zip(positive_h, h_indices) if u[k] not in positive), None)
            if bad is None:
                return u
            u = tuple(u[k] for k in reflection[bad])

    orbit, stack = {identity}, [identity]
    while stack:
        U = stack.pop()
        for C in glue:
            V = reduce(tuple(U[k] for k in C))
            if V not in orbit:
                orbit.add(V)
                stack.append(V)
    return len(orbit)
