"""
Spherical varieties assembled orbit by orbit (PLAN.md S6d, docs/S6d.md).

T-fixed points of a spherical variety can lie in non-closed G-orbits (for
P^1 x P^1 > SL_2/T two of them lie in the open orbit), so the fixed-point
data is assembled orbit by orbit. A G-orbit O contains T-fixed points iff
its stabilizers contain a maximal torus; then, for a base point x with
stabilizer H > T,
    O^T = N_G(T).x = W/W_H,   W_H = N_H(T)/T,
    T_{w.x} X = w(Phi_G - Phi_H) + w(N_x),
where Phi_H are the roots of H and N_x is the normal space to O at x (a
W_H-invariant multiset of weights). So the whole of X^T is determined by
one base point per such orbit.

For a wonderful variety with spherical roots Sigma and S^p (the simple roots
of the parabolic P(X)), the orbit O_I (I c Sigma) fibres over G/P_I with
fibre the satellite L_I/H_{L,I}, where L_I is the Levi subgroup on
S^p + supp(I). The orbit has T-fixed points iff the satellite does, and
then (docs/S6d.md, section 3)
    Phi_H = (Phi^+ - Phi_{L_I}) + Phi_{H_{L,I}},
    N_x   = the W_{L_I}-averages of -gamma, gamma in Sigma - I,
the latter provided the reflections of W_{H_{L,I}} span the roots of L_I
(checked; otherwise the normal weights are not determined by this data).
All weights are in simple-root coordinates of G (the torus of G_ad).
"""

from dataclasses import dataclass
from fractions import Fraction
from itertools import combinations

from bbcells.core import FixedPointData
from bbcells.frontends.flag import word_label
from bbcells.linalg import rank as matrix_rank, solve
from bbcells.rootsystem import RootSystem

_WEYL_LIMIT = 60000


def _negate(v):
    return tuple(-c for c in v)


def root_subsystem(R, generators):
    """the root subsystem generated by the given roots (closure under their
    reflections), as a set of roots in simple-root coordinates"""
    def reflect(beta, gamma):
        c = R.coroot_pairing(beta, gamma)
        return tuple(g - c * b for g, b in zip(gamma, beta))

    roots = set()
    for g in generators:
        roots.add(tuple(g))
        roots.add(_negate(g))
    frontier = list(roots)
    while frontier:
        new = []
        for gamma in frontier:
            for beta in list(roots):
                image = reflect(beta, gamma)
                if image not in roots:
                    roots.add(image)
                    new.append(image)
        frontier = new
    return roots


def _all_roots(R):
    return set(R.positive_roots) | {_negate(b) for b in R.positive_roots}


def _reflection(R, beta, v):
    """s_beta(v) for a root beta and any vector v (simple-root coordinates)"""
    c = 2 * R.inner(beta, v) / R.inner(beta, beta)
    if c.denominator != 1:
        raise ValueError("s_%r does not preserve the lattice at %r" % (beta, v))
    return tuple(x - int(c) * b for x, b in zip(v, beta))


def homogeneous_fixed_points(cartan_type, generators=(), component_reflections=(),
                             unipotent_roots=(), normal=()):
    """fixed points of T on an orbit G/H with T c H, and their tangent weights.

    H is described by its roots: the root subsystem generated by `generators`
    (the reductive part, Borel-de Siebenthal) and the W_H-orbits of
    `unipotent_roots`; W_H = N_H(T)/T is generated by the reflections of the
    subsystem and by `component_reflections` (roots whose reflections lie in
    N_H(T), e.g. Knop's <s_{a_1}>.SL(3) in G2). `normal` are the weights of the
    normal space of the orbit at eH. Returns {label: weights} over W/W_H,
    labelled by a minimal-length representative.
    >>> points = homogeneous_fixed_points("A1")                # SL_2/T
    >>> sorted(sorted(w) for w in points.values())
    [[(-1,), (1,)], [(-1,), (1,)]]
    >>> homogeneous_fixed_points("A2", unipotent_roots=[(1, 0), (0, 1), (1, 1)])["e"]  # G/B
    ((-1, -1), (-1, 0), (0, -1))
    """
    R = RootSystem(cartan_type)
    roots = _all_roots(R)
    phi_sym = root_subsystem(R, generators)
    if not phi_sym <= roots:
        raise ValueError("the generators do not span a subsystem of roots")
    reflections = sorted(phi_sym) + [tuple(b) for b in component_reflections]
    if not all(b in roots for b in reflections):
        raise ValueError("component reflections must be in roots")
    for b in component_reflections:
        if {_reflection(R, tuple(b), g) for g in phi_sym} != phi_sym:
            raise ValueError("s_%r does not normalize the reductive part" % (tuple(b),))
    # Phi_H: the reductive part and the W_H-orbits of the unipotent roots
    phi_h, frontier = set(phi_sym), [tuple(b) for b in unipotent_roots]
    while frontier:
        beta = frontier.pop()
        if beta in phi_h:
            continue
        if beta not in roots:
            raise ValueError("%r is not a root" % (beta,))
        phi_h.add(beta)
        frontier.extend(_reflection(R, s, beta) for s in reflections)
    if {b for b in phi_h if _negate(b) in phi_h} != phi_sym:
        raise ValueError("the unipotent roots meet their negatives: H is not "
                         "described by these generators")
    for a in phi_h:
        for b in phi_h:
            total = tuple(x + y for x, y in zip(a, b))
            if total in roots and total not in phi_h:
                raise ValueError("the roots of H are not closed: %r + %r" % (a, b))
    normal = [tuple(v) for v in normal]
    for s in reflections:
        if sorted(_reflection(R, s, v) for v in normal) != sorted(normal):
            raise ValueError("the normal weights are not W_H-invariant (s_%r)" % (s,))
    complement = sorted(roots - phi_h)

    # W_H is a reflection subgroup; by Dyer (Reflection subgroups of Coxeter
    # systems, 1990) each coset w W_H has a unique element of minimal length,
    # the w with w(beta) > 0 for every positive root beta of W_H
    positive = set(R.positive_roots)
    positive_h = [b for b in root_subsystem(R, reflections) if b in positive]
    roots_list = sorted(roots)
    index = {b: i for i, b in enumerate(roots_list)}
    simple = [tuple(index[R.reflect(i, b)] for b in roots_list) for i in range(R.rank)]
    permutation = {(): tuple(range(len(roots_list)))}
    points = {}
    for _, word in R.orbit(set(), limit=_WEYL_LIMIT):      # all of W, by length
        if word:                                           # s_{word[0]} o (the rest)
            rest = permutation[word[1:]]
            permutation[word] = tuple(simple[word[0]][k] for k in rest)
        w = permutation[word]
        if all(roots_list[w[index[b]]] in positive for b in positive_h):
            points[word_label(word)] = (tuple(roots_list[w[index[b]]] for b in complement) +
                                        tuple(R.apply_word(word, v) for v in normal))
    return points


def in_coordinates(points, simple_roots):
    """rewrite the weights of `points` (simple-root coordinates) in other
    coordinates, given the images of the simple roots
    >>> in_coordinates({"e": ((1,), (-1,))}, [(1, -1)])     # sl_2 in eps-coordinates
    {'e': ((1, -1), (-1, 1))}
    """
    def convert(weight):
        return tuple(sum(c * col[k] for c, col in zip(weight, simple_roots))
                     for k in range(len(simple_roots[0])))

    return {label: tuple(convert(w) for w in weights) for label, weights in points.items()}


@dataclass(frozen=True)
class OrbitDatum(object):
    """a G-orbit with T-fixed points: its base point stabilizer H > T and the
    normal weights there (see homogeneous_fixed_points)"""
    name: str
    generators: tuple = ()
    component_reflections: tuple = ()
    unipotent_roots: tuple = ()
    normal: tuple = ()


def assemble(cartan_type, orbits, name=""):
    """FixedPointData of the union of the given orbits (all orbits of X that
    contain T-fixed points), in simple-root coordinates
    >>> X = assemble("A1", [OrbitDatum("open"),
    ...                     OrbitDatum("closed", unipotent_roots=[(1,)], normal=[(-1,)])])
    >>> X.points, X.weights_of("closed:e")                  # P^1 x P^1 > SL_2/T
    (('open:e', 'open:s1', 'closed:e', 'closed:s1'), ((-1,), (-1,)))
    """
    rank = RootSystem(cartan_type).rank
    labels, weights, annotations, dims = [], [], [], set()
    for orbit in orbits:
        points = homogeneous_fixed_points(cartan_type, orbit.generators,
                                          orbit.component_reflections,
                                          orbit.unipotent_roots, orbit.normal)
        for word, wts in points.items():
            labels.append("%s:%s" % (orbit.name, word))
            weights.append(wts)
            annotations.append({"orbit": orbit.name, "word": word})
            dims.add(len(wts))
    if len(dims) != 1:
        raise ValueError("the orbits give tangent spaces of dimensions %s" % sorted(dims))
    return FixedPointData(dims.pop(), rank, tuple(labels), tuple(weights),
                          name=name, annotations=tuple(annotations))


def _support(v):
    return {i for i, c in enumerate(v) if c}


def levi_projection(R, levi, v):
    """the W_L-average of v, i.e. its orthogonal projection onto the
    complement of the roots of the Levi subgroup on `levi`
    >>> levi_projection(RootSystem("A2"), {0}, (0, -2))
    (-1, -2)
    """
    levi = sorted(levi)
    if not levi:
        return tuple(v)
    simple = lambda i: tuple(int(k == i) for k in range(R.rank))
    gram = [[R.inner(simple(i), simple(j)) for j in levi] for i in levi]
    rhs = [R.inner(simple(i), v) for i in levi]
    c = solve(gram, rhs)
    result = [Fraction(x) for x in v]
    for coefficient, i in zip(c, levi):
        result[i] -= coefficient
    if any(x.denominator != 1 for x in result):
        raise ValueError("the W_L-average of %r is not integral" % (v,))
    return tuple(int(x) for x in result)


def wonderful_orbits(cartan_type, spherical_roots, satellite, parabolic=()):
    """OrbitData of a wonderful variety from its spherical roots, S^p
    (`parabolic`, 0-based simple roots) and the satellites: satellite(I) for
    nonempty I c range(len(spherical_roots)) returns None if the satellite
    L_I/H_{L,I} has no T-fixed points, else a dict with keys among
    generators, component_reflections, unipotent_roots describing
    H_{L,I} > T inside L_I (L_I = the Levi subgroup on S^p + supp(I))"""
    R = RootSystem(cartan_type)
    sigma = [tuple(g) for g in spherical_roots]
    for g in sigma:
        if any(R.coroot_pairing(tuple(int(k == i) for k in range(R.rank)), g)
               for i in parabolic):
            raise ValueError("spherical root %r is not orthogonal to S^p" % (g,))
    orbits = []
    for size in range(len(sigma) + 1):
        for I in combinations(range(len(sigma)), size):
            levi = set(parabolic).union(*(_support(sigma[j]) for j in I))
            if I:
                data = satellite(I)
                if data is None:
                    continue
            else:
                simple = [tuple(int(k == i) for k in range(R.rank)) for i in sorted(levi)]
                data = {"generators": simple}
            phi_l = set(R.positive_roots_of(levi))
            phi_l |= {_negate(b) for b in phi_l}
            generators = [tuple(b) for b in data.get("generators", ())]
            components = [tuple(b) for b in data.get("component_reflections", ())]
            if not all(b in phi_l for b in generators + components):
                raise ValueError("satellite %r: roots outside L_I" % (I,))
            normal_roots = [j for j in range(len(sigma)) if j not in I]
            if normal_roots and levi and matrix_rank(generators + components) != len(levi):
                raise ValueError("satellite %r: W_H has invariants on the roots of L_I, "
                                 "the normal weights are not determined" % (I,))
            unipotent = [b for b in R.positive_roots if b not in phi_l]
            unipotent += [tuple(b) for b in data.get("unipotent_roots", ())]
            normal = [levi_projection(R, levi, _negate(sigma[j])) for j in normal_roots]
            label = "O" + "".join(str(j + 1) for j in I) if I else "closed"
            orbits.append(OrbitDatum(label, tuple(generators), tuple(components),
                                     tuple(unipotent), tuple(normal)))
    return orbits


def wonderful_variety(cartan_type, spherical_roots, satellite, parabolic=(), name=""):
    """FixedPointData of a wonderful variety (see wonderful_orbits)
    >>> X = wonderful_variety("A1", [(1,)], lambda I: {})    # P^1 x P^1 for SL_2
    >>> X.dim, len(X)
    (2, 4)
    """
    return assemble(cartan_type, wonderful_orbits(cartan_type, spherical_roots, satellite,
                                                  parabolic), name=name)


def _runs(indices):
    """maximal runs of consecutive integers
    >>> _runs((0, 1, 3))
    [[0, 1], [3]]
    """
    runs = []
    for i in sorted(indices):
        if runs and runs[-1][-1] == i - 1:
            runs[-1].append(i)
        else:
            runs.append([i])
    return runs


def complete_quadrics(n):
    """complete quadrics in P^{n-1}: the wonderful compactification of
    PGL_n/PO_n, spherical roots 2 alpha_i. Satellites: L_I = S(prod GL_k) over
    the blocks of I, H = S(prod O_k); T-fixed points iff every block has
    k <= 2, and then W_H is generated by the reflections of the blocks
    >>> X = complete_quadrics(3)                             # complete conics
    >>> X.dim, len(X)
    (5, 12)
    """
    if n < 2:
        raise ValueError("need n >= 2")
    r = n - 1
    unit = lambda i: tuple(int(k == i) for k in range(r))

    def satellite(I):
        if any(len(run) > 1 for run in _runs(I)):
            return None                  # a block SL_k/SO_k with k >= 3
        return {"component_reflections": [unit(i) for i in I]}

    sigma = [tuple(2 * c for c in unit(i)) for i in range(r)]
    return wonderful_variety("A%d" % r, sigma, satellite,
                             name="complete quadrics in P^%d" % (n - 1))


def complete_skew_forms(n):
    """complete skew forms on k^{2n}: the wonderful compactification of
    PGL_{2n}/PSp_{2n}, S^p = {alpha_1, alpha_3, ...}, spherical roots
    alpha_{2i-1} + 2 alpha_{2i} + alpha_{2i+1}. Only the closed orbit has
    T-fixed points (Sp_{2k} has full rank in SL_{2k} only for k = 1)
    >>> X = complete_skew_forms(2)                           # P^5 = P(Lambda^2 k^4)
    >>> X.dim, len(X)
    (5, 6)
    """
    if n < 1:
        raise ValueError("need n >= 1")
    r = 2 * n - 1
    sigma = [tuple(1 if k in (2 * i, 2 * i + 2) else 2 if k == 2 * i + 1 else 0
                   for k in range(r)) for i in range(n - 1)]
    return wonderful_variety("A%d" % r, sigma, lambda I: None,
                             parabolic=tuple(range(0, r, 2)),
                             name="complete skew forms on k^%d" % (2 * n))
