"""
Complete symmetric varieties from Satake diagrams (docs/S6d.md, section 6).

For an involution theta of G with Satake diagram (black nodes, arrows), the
complete symmetric variety of De Concini-Procesi is the wonderful
compactification of G_ad/G_ad^theta. Its combinatorial data:

  * theta acts on characters by theta = -w_black o eps, where eps permutes
    the white nodes along the arrows and the black nodes by the opposition
    involution of the black subdiagram;
  * the spherical roots are alpha - theta(alpha), one for each arrow orbit
    of white simple roots, and S^p is the set of black nodes;
  * the satellite of I is the symmetric pair (L_I, theta), whose Satake
    diagram is the subdiagram on S^p + supp(I). It has T-fixed points iff
    every component of that subdiagram is of equal rank, i.e. eps equals
    the opposition involution -w_0 there. An equal-rank involution is then
    Ad(t_j) for a Borel-de Siebenthal node j with alpha_j(t_j) = -1 and
    alpha_i(t_j) = 1 otherwise, found by recognizing the subdiagram in
    Bourbaki numbering; W_H is the stabilizer of t_j in W_L (acting on the
    adjoint torus), which need not be generated by reflections.

Every recognition is cross-checked: dim K computed from the Satake diagram
(rank + |Phi| - r - (|Phi| - |Phi_black|)/2, r the number of white orbits)
must equal rank + #{roots fixed by t_j}.
"""

from itertools import permutations

from bbcells.frontends import spherical
from bbcells.oracles import _classify_component
from bbcells.rootsystem import RootSystem


def _unit(i, r):
    return tuple(int(k == i) for k in range(r))


def _pairing(R, v, i):
    """<v, alpha_i^vee> for v in simple-root coordinates"""
    return sum(c * R.cartan[i][j] for j, c in enumerate(v))


def longest_word(R, nodes):
    """a reduced word (0-based) of the longest element of W_nodes
    >>> longest_word(RootSystem("A2"), {0, 1})
    (0, 1, 0)
    """
    nodes = sorted(nodes)
    v = [0] * R.rank
    for b in R.positive_roots_of(nodes):
        v = [x + y for x, y in zip(v, b)]              # 2 rho of the subsystem
    word = []
    while True:
        i = next((i for i in nodes if _pairing(R, v, i) > 0), None)
        if i is None:
            return tuple(reversed(word))
        v = list(R.reflect(i, v))
        word.append(i)


def opposition(R, nodes):
    """the involution i -> j of nodes with w_0(alpha_i) = -alpha_j"""
    word = longest_word(R, nodes)
    result = {}
    for i in nodes:
        image = R.apply_word(word, _unit(i, R.rank))
        (j,) = [k for k, c in enumerate(image) if c]
        result[i] = j
    return result


def _components(R, nodes):
    remaining, components = set(nodes), []
    while remaining:
        start = min(remaining)
        component, stack = {start}, [start]
        while stack:
            i = stack.pop()
            for j in list(remaining):
                if j not in component and R.cartan[i][j] != 0:
                    component.add(j)
                    stack.append(j)
        remaining -= component
        components.append(sorted(component))
    return components


class SatakeDiagram(object):
    """a Satake diagram on a Cartan type: black nodes and arrows (1-based)
    >>> S = SatakeDiagram("A3", black=(), arrows=[(1, 3)])      # su(2, 2)
    >>> S.spherical_roots
    [(1, 0, 1), (0, 2, 0)]
    """

    def __init__(self, cartan_type, black=(), arrows=(), name=""):
        self.R = R = RootSystem(cartan_type)
        self.name = name or "%s(black %s, arrows %s)" % (R.name, sorted(black), sorted(arrows))
        self.black = {i - 1 for i in black}
        self.white = [i for i in range(R.rank) if i not in self.black]
        self.eps = {}
        for a, b in arrows:
            a, b = a - 1, b - 1
            if a in self.black or b in self.black:
                raise ValueError("arrows join white nodes only")
            self.eps[a], self.eps[b] = b, a
        for i in self.white:
            self.eps.setdefault(i, i)
        for component in _components(R, self.black):
            self.eps.update(opposition(R, component))
        self.w_black = longest_word(R, self.black)
        # one spherical root per eps-orbit of white nodes
        self.spherical_roots, self.orbit_of = [], {}
        for i in self.white:
            gamma = self.gamma(i)
            if gamma != self.gamma(self.eps[i]):
                raise ValueError("alpha - theta(alpha) differs along an arrow: not a Satake diagram")
            if gamma not in self.spherical_roots:
                self.spherical_roots.append(gamma)
            self.orbit_of[i] = self.spherical_roots.index(gamma)

    def theta(self, v):
        """theta = -w_black o eps on characters (simple-root coordinates)"""
        image = [0] * self.R.rank
        for i, c in enumerate(v):
            image[self.eps[i]] += c
        return tuple(-c for c in self.R.apply_word(self.w_black, image))

    def gamma(self, i):
        alpha = _unit(i, self.R.rank)
        return tuple(a - b for a, b in zip(alpha, self.theta(alpha)))

    def dim_k(self, nodes):
        """dim K of the real form of the subdiagram on `nodes` (with its centre
        in the Levi counted separately: rank + roots only)"""
        R = self.R
        roots = 2 * len(R.positive_roots_of(nodes))
        black = 2 * len(R.positive_roots_of(set(nodes) & self.black))
        orbits = {frozenset((i, self.eps[i])) for i in nodes if i not in self.black}
        return len(nodes) + roots - len(orbits) - (roots - black) // 2

    def satellite_node(self, component):
        """the Borel-de Siebenthal node (ambient, 0-based) of an equal-rank
        component, None for a compact one; raises if the component is not of
        equal rank or not recognized"""
        R = self.R
        if not any(i not in self.black for i in component):
            return None
        if any(self.eps[i] not in component for i in component):
            raise _NotEqualRank()
        if opposition(R, component) != {i: self.eps[i] for i in component}:
            raise _NotEqualRank()
        letter, rank = _classify_component(R.cartan, component)
        candidates = [letter]
        if letter == "B" and rank >= 3:
            candidates = ["B", "C"]
        for letter in candidates:
            standard = RootSystem("%s%d" % (letter, rank))
            for phi in _isomorphisms(standard, R, component):
                black = {k + 1 for k in range(rank) if phi[k] in self.black}
                arrows = {(k + 1, l + 1) for k in range(rank) for l in range(rank)
                          if k < l and phi[k] not in self.black and self.eps[phi[k]] == phi[l]}
                j = _recognize(letter, rank, black, arrows)
                if j is not None:
                    node = phi[j - 1]
                    self._check_dimension(component, node)
                    return node
        raise ValueError("unrecognized equal-rank Satake subdiagram on nodes %s"
                         % [i + 1 for i in component])

    def _check_dimension(self, component, node):
        fixed = sum(1 for b in self.R.positive_roots_of(component) if b[node] % 2 == 0)
        if len(component) + 2 * fixed != self.dim_k(component):
            raise AssertionError("dim K mismatch for nodes %s" % [i + 1 for i in component])

    def satellite(self, I):
        """satellite data of the orbit O_I for wonderful_orbits, or None"""
        R = self.R
        nodes = set(self.black) | {i for i in self.white if self.orbit_of[i] in I}
        signs = {}
        try:
            for component in _components(R, nodes):
                node = self.satellite_node(component)
                if node is not None:
                    signs[node] = -1
        except _NotEqualRank:
            return None
        parity = lambda v: sum(v[j] for j in signs) % 2           # 1 iff alpha(t) = -1
        levi_roots = R.positive_roots_of(nodes)
        fixed = [b for b in levi_roots if parity(b) == 0]
        component_reflections = [
            b for b in levi_roots if parity(b) == 1 and
            all(R.coroot_pairing(b, _unit(i, R.rank)) % 2 == 0 for i in nodes)]
        elements = _non_reflection_part(R, sorted(nodes), parity,
                                        fixed + component_reflections)
        return {"generators": fixed, "component_reflections": component_reflections,
                "component_elements": elements}

    def orbits(self, strict=False):
        return spherical.wonderful_orbits(self.R.name, self.spherical_roots, self.satellite,
                                          parabolic=tuple(sorted(self.black)), strict=strict)

    def fixed_point_data(self, strict=False):
        """the fixed-point data; orbits beyond condition (R) (Hermitian
        satellites) are accepted only if the result satisfies the holomorphic
        Lefschetz identity and is independent of the cocharacter"""
        orbits = self.orbits(strict)
        X = spherical.assemble(self.R.name, orbits,
                               name="complete symmetric variety %s" % self.name)
        if any(orbit.note for orbit in orbits):
            from bbcells.core import bb_cells
            report = bb_cells(X).check()
            if not report.ok:
                raise ValueError("normal weights beyond condition (R) fail the checks:\n%s"
                                 % report)
        return X


class _NotEqualRank(Exception):
    pass


def _isomorphisms(standard, R, component):
    """all bijections phi: standard nodes -> component preserving the Cartan matrix"""
    k = len(component)
    order = list(range(k))
    result = []

    def extend(phi):
        if len(phi) == k:
            result.append(tuple(phi))
            return
        a = len(phi)
        for node in component:
            if node in phi:
                continue
            if all(standard.cartan[a][b] == R.cartan[node][phi[b]] and
                   standard.cartan[b][a] == R.cartan[phi[b]][node] for b in range(a)):
                extend(phi + [node])

    extend([])
    return result


def _recognize(letter, k, black, arrows):
    """Borel-de Siebenthal node (1-based, Bourbaki) of an equal-rank Satake
    diagram in standard numbering, or None if the pattern does not match"""
    white = [i for i in range(1, k + 1) if i not in black]
    nodes = set(range(1, k + 1))
    if letter == "A":
        n = k + 1
        p = len({frozenset((i, n - i)) & nodes for i in white})
        expected_white = set(range(1, p + 1)) | set(range(n - p, n))
        expected_arrows = {(i, n - i) for i in range(1, p + 1) if i < n - i}
        if set(white) == expected_white and arrows == expected_arrows:
            return p
        return None
    if letter == "B":
        p = len(white)
        if set(white) == set(range(1, p + 1)) and not arrows:
            q = 2 * k + 1 - p
            return (p if p % 2 == 0 else q) // 2
        return None
    if letter == "C":
        if not black and not arrows:
            return k                                                 # CI
        p = len(white)
        if (set(white) == set(range(2, 2 * p + 1, 2)) and not arrows):
            return p                                                 # CII
        return None
    if letter == "D":
        p = len(white) - (1 if (k - 1, k) in arrows else 0)
        di_white = set(range(1, p + 1)) if p <= k - 2 else nodes
        di_arrows = {(k - 1, k)} if p == k - 1 else set()
        if set(white) == di_white and arrows == di_arrows and p % 2 == 0:
            return p // 2                                            # DI(p, 2k - p)
        if k % 2 == 0:
            iii = (set(range(2, k + 1, 2)), set())
        else:
            iii = (set(range(2, k, 2)) | {k}, {(k - 1, k)})
        if (set(white), arrows) == iii:
            return k                                                 # DIII
        return None
    table = {("E", 6): [((), {(1, 6), (3, 5)}, 2),                   # EII
                        ((3, 4, 5), {(1, 6)}, 1)],                    # EIII
             ("F", 4): [((), set(), 1), ((1, 2, 3), set(), 4)],      # FI, FII
             ("G", 2): [((), set(), 2)]}
    for b, a, j in table.get((letter, k), []):
        if black == set(b) and arrows == a:
            return j
    return None


def _non_reflection_part(R, nodes, parity, reflection_roots):
    """words of coset representatives of Stab_{W_L}(t) modulo its reflection
    subgroup (the identity omitted)"""
    roots, index, table = spherical.weyl_table(R.name)
    positive = {index[b] for b in R.positive_roots}
    positive_refl = [index[b] for b in spherical.root_subsystem(R, reflection_roots)
                     if b in set(R.positive_roots)]
    simple = [(i, index[_unit(i, R.rank)]) for i in nodes]
    nodes = set(nodes)
    elements = []
    for word, w in table:
        if not word or not set(word) <= nodes:
            continue                                 # not in W_L (reduced words)
        if any(parity(roots[w[k]]) != parity(_unit(i, R.rank)) for i, k in simple):
            continue                                 # w does not fix t
        if all(w[k] in positive for k in positive_refl):
            elements.append(word)                    # minimal in its coset
    return sorted(elements, key=lambda word: (len(word), word))


# Satake diagrams (Araki; Helgason, Table VI), Bourbaki numbering
def diagram(kind, *parameters):
    """the Satake diagram of a named real form
    >>> diagram("AIII", 1, 2).spherical_roots          # PGL_3/GL_2
    [(1, 1)]
    >>> diagram("CII", 1, 2).spherical_roots           # HP^2
    [(1, 2, 1)]
    """
    kind = kind.upper()
    name = "%s%s" % (kind, "(%s)" % ", ".join(map(str, parameters)) if parameters else "")
    if kind == "AI":
        (n,) = parameters
        return SatakeDiagram("A%d" % (n - 1), name=name)
    if kind == "AII":
        (n,) = parameters
        return SatakeDiagram("A%d" % (2 * n - 1), black=range(1, 2 * n, 2), name=name)
    if kind == "AIII":
        p, q = sorted(parameters)
        n = p + q
        return SatakeDiagram("A%d" % (n - 1), black=range(p + 1, q),
                             arrows=[(i, n - i) for i in range(1, p + 1) if i < n - i],
                             name=name)
    if kind == "BI":
        p, q = sorted(parameters)
        if (p + q) % 2 == 0:
            raise ValueError("BI needs p + q odd")
        n = (p + q - 1) // 2
        return SatakeDiagram("B%d" % n, black=range(p + 1, n + 1), name=name)
    if kind == "CI":
        (n,) = parameters
        return SatakeDiagram("C%d" % n, name=name)
    if kind == "CII":
        p, q = sorted(parameters)
        n = p + q
        black = set(range(1, 2 * p, 2)) | set(range(2 * p + 1, n + 1))
        return SatakeDiagram("C%d" % n, black=black, name=name)
    if kind == "DI":
        p, q = sorted(parameters)
        if (p + q) % 2:
            raise ValueError("DI needs p + q even")
        n = (p + q) // 2
        if p <= n - 2:
            return SatakeDiagram("D%d" % n, black=range(p + 1, n + 1), name=name)
        if p == n - 1:
            return SatakeDiagram("D%d" % n, arrows=[(n - 1, n)], name=name)
        return SatakeDiagram("D%d" % n, name=name)
    if kind == "DIII":
        (n,) = parameters
        if n % 2 == 0:
            return SatakeDiagram("D%d" % n, black=range(1, n, 2), name=name)
        return SatakeDiagram("D%d" % n, black=range(1, n - 1, 2), arrows=[(n - 1, n)],
                             name=name)
    exceptional = {"EI": ("E6", (), ()), "EII": ("E6", (), [(1, 6), (3, 5)]),
                   "EIII": ("E6", (3, 4, 5), [(1, 6)]), "EIV": ("E6", (2, 3, 4, 5), ()),
                   "FI": ("F4", (), ()), "FII": ("F4", (1, 2, 3), ()), "G": ("G2", (), ())}
    if kind in exceptional:
        cartan_type, black, arrows = exceptional[kind]
        return SatakeDiagram(cartan_type, black=black, arrows=arrows, name=name)
    raise ValueError("unknown real form %r (E7 and E8 are too large for this front end)" % kind)


def complete_symmetric_variety(kind, *parameters, strict=False):
    """FixedPointData of the complete symmetric variety of a named real form
    >>> X = complete_symmetric_variety("AI", 3)                 # complete conics
    >>> X.dim, len(X)
    (5, 12)
    """
    return diagram(kind, *parameters).fixed_point_data(strict)
